version: "3"

services:

  server:
    image: jetbrains/teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - ./datadir:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs
    user: "1000:1000"

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    environment:
      - SERVER_URL=http://server:8111
      - AGENT_NAME=Regular Agent with Docker support
      - DOCKER_IN_DOCKER=start
    privileged: true
